apiVersion: batch/v1
kind: Job
metadata:
  namespace: monitoring
  name: grafana-chown
spec:
  template:
    spec:
      containers:
      - name: grafana-chown
        command: ["chown", "-R", "472:472", "/var/lib/grafana"]
        image: busybox
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: grafana-data
          subPath: grafana
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana-data
        persistentVolumeClaim:
          claimName: monitoring-pvcnode-exporter.yml
            promotheus.yml
      restartPolicy: Never

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: admin
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: ghcadmin
        - name: GF_INSTALL_PLUGINS
          value: grafana-piechart-panel
        volumeMounts:
          - name: grafana-data
            subPath: grafana
            mountPath: /var/lib/grafana
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: monitoring-pvc
      securityContext:
        fsGroup: 472
        runAsUser: 472
      restartPolicy: Always
  selector:
    matchLabels:
      app: grafana

---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: grafana-svc
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    nodePort: 30300
  type: NodePort
