apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: monitoring
  name: node-exporter
  labels:
    app: node-exporter
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
      - name: node-exporter
        image: prom/node-exporter
        env:
        - name: TZ
          value: Asia/Shanghai
        ports:
        - containerPort: 9100
          protocol: TCP
          name: http
      hostNetwork: true
      hostPID: true
      tolerations:
      - effect: NoSchedule
        operator: Exists

#---
#kind: Service
#apiVersion: v1
#metadata:
#  namespace: monitoring
#  name: node-exporter-service
#  labels:
#    app: node-exporter
#spec:
#  ports:
#  - name: http
#    port: 9100
#    nodePort: 30910
#    protocol: TCP
#  type: NodePort
#  selector:
#    app: node-exporter
